---
engine: knitr
---

# Introduction {.unnumbered}

**Frequentist statistics** is founded on the idea that probability represents the frequency with which something happens.

:::{.column-margin}
**Frequentist statistics** also known as frequentist interference, is a type of statistical approach where conclusions are made based on the frequency of an event. This statistical approach determines the probability of a long-term experiment, meaning the experiment is repeated under the same set of conditions to obtain an outcome. In frequentist statistics the population parameters are fixed, but unknown, and the data observed in experiments are random. (<a href="https://deepai.org/machine-learning-glossary-and-terms/frequentist-statistics">deepai.org</a>)

:::

**Bayesian statistics** on the other hand, is concerned
with how probabilities represent how uncertain we are about a piece of
information.

:::{.column-margin}
**Bayesian statistics** uses Bayesian reasoning is the formal process that we use to update our beliefs about the world once we’ve observed some data.
Ba
:::
